name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Twelve Step Programme
    steps:
    - uses: jclulow/action-agogo@main
      with:
        script: |
          banner info
          id -a
          uname -a
          uptime

          banner tools
          pkg install git build-essential 

          banner rustup
          export RUSTUP_HOME=/rustup
          export CARGO_HOME=/rustup
          export PATH="$CARGO_HOME/bin:$PATH"
          curl -sSf https://sh.rustup.rs | bash -s -- \
              -y \
              --default-toolchain stable \
              --no-modify-path

          banner env
          env

          cd testing

          banner build
          cargo build --release

          banner test
          cargo test --release
        secret: ${{ secrets.THE_PASSWORD }}
        baseurl: https://sys.illumos.org/buildomat
