name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Twelve Step Programme
    steps:
    - uses: jclulow/action-agogo@main
      with:
        script: |
          banner info
          id -a
          uname -a
          uptime

          banner tools
          pkg install git build-essential 

          banner env
          env

          cd testing

          banner build
          cargo build --release

          banner test
          cargo test --release
        secret: ${{ secrets.THE_PASSWORD }}
        baseurl: https://sys.illumos.org/buildomat
