name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Twelve Step Programme
    steps:
    - id: ws1
      name: whatever step 1
      uses: jclulow/action-agogo@main
      with:
        script: |
          id -a
          find -ls /var/tmp
          env
        secret: ${{ secrets.THE_PASSWORD }}
    - id: ws2
      name: look at files...
      run: pwd && find . -ls
